#!/usr/bin/env php
<?php
use Erliz\DeployerCfg\Command;

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Command\RenderCommand());
$application->add(new Command\ListConfigsCommand());

$application->run();